# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "daf4359349b8033a4165df358aa6e05c"
name = "Tryon"
application_url = "https://tryonline.vercel.app"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://tryonline.vercel.app" ]

[pos]
embedded = false
